version: '3.8'

services:

  backend:
    build: ./backend
    container_name: gamematch-backend
    ports:
      - "5000:5000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DB_HOST=mysql
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - RAWG_API_KEY=${RAWG_API_KEY}
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend:/app
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: gamematch-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/ulbs_gamematch.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  mysql_data: